alias ls='ls -F --color=auto'
alias ll='ls -lah  --color=auto'
alias gh='history|grep'
alias lt='ls --human-readable --size -1 -S --classify --color=auto'
alias count='find . -type f | wc -l'
alias cpv='rsync -ah --info=progress2'